# Default values for compreface-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

postgres:
  repository: postgres
  pullPolicy: Always
  db_name: frs
  db_port: 5432
  db_user: compreface
  name: acid-compreface-postgres
  size: 25Gi
  replicas: 1
  version: 14

core:
  enabled: false
  repository: exadel/compreface-core
  pullPolicy: Always
  tag: 0.6.1
  port: 3000
  replicas: 1
  name: compreface-core

api:
  repository: exadel/compreface-api
  pullPolicy: Always
  tag: 0.6.1
  port: 8080
  replicas: 1
  name: compreface-api
  coreUrl: http://192.168.1.11:3000

admin:
  repository: exadel/compreface-admin
  pullPolicy: Always
  tag: 0.6.1
  port: 8080
  replicas: 1
  name: compreface-admin

fe:
  repository: exadel/compreface-fe
  pullPolicy: Always
  tag: 0.6.1
  port: 80
  replicas: 1
  name: compreface-fe


imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "compreface"

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
